[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://ko-fi.com/fither"
    weight = 5
    
# Social Media Configuration

[[social]]
    identifier = "x"
    name = "X"
    url = "https://x.com/fither_briano"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://instagram.com/fitherbroto"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/fitherbriano"
    weight = 3
